#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"

export PATH="$HERE"/bin:"$HERE"/usr/bin:"$PATH"
export LD_LIBRARY_PATH="$HERE"/usr/lib:"$LD_LIBRARY_PATH"

export I3_NEWS_HOME=$HOME/.config/i3_news
export I3_NEWS_BIN_PATH="$HERE"/usr/local/bin/i3_news
export ZSCROLL_EXE="python3 $HERE"/usr/local/bin/zscroll
export BSCROLL_SCRIPT="$HERE"/usr/local/bin/bscroll

if [ -z ${I3_NEWS_BROWSER_CMD+x} ]; then
    export I3_NEWS_BROWSER_CMD=$BROWSER
fi
if [ -z ${ZSCROLL_INTERVAL+x} ]; then
    export ZSCROLL_INTERVAL=10
fi
if [ -z ${ZSCROLL_DELAY+x} ]; then
    export ZSCROLL_DELAY=0.6
fi
if [ -z ${ZSCROLL_WIDTH+x} ]; then
    export ZSCROLL_WIDTH=40
fi
if [ -z ${BSCROLL_INTERVAL+x} ]; then
    export BSCROLL_INTERVAL=16
fi
if [ -z ${BSCROLL_DELAY+x} ]; then
    export BSCROLL_DELAY=0.5
fi
if [ -z ${BSCROLL_WIDTH+x} ]; then
    export BSCROLL_WIDTH=60
fi

if ! type newsboat > /dev/null; then
    echo "Newsboat binary not found in the system"
    exit 1
fi

newsboat_reload() {
    if type pgrep > /dev/null; then
        while pgrep newsboat > /dev/null; do sleep 2; done
    fi
    mkdir -p $I3_NEWS_HOME;
    if [ -z "$( ls -A $I3_NEWS_HOME )" ]; then
        echo "No configurations found in " $I3_NEWS_HOME;
        return
    fi
    for dir in $I3_NEWS_HOME/*/
    do
        dir=${dir%*/}
        echo "i3-news: Reloading news for config ${dir##*/}"
        newsboat -x reload -c ${dir}/cache.db -u ${dir}/urls --vacuum
    done
}

if [ "$1" = "reload" ]; then
    newsboat_reload;
# polybar 
elif [ "$1" = "open" ]; then
    all_args=("$@")
    url="$($I3_NEWS_BIN_PATH --get-url ${all_args[@]:1})"
    if [ -n ${I3_NEWS_BROWSER_CMD+x} ]; then
        $I3_NEWS_BROWSER_CMD $url
    else
        xdg-open $url
    fi
elif [ "$1" = "zscroll" ]; then
    all_args=("$@")
    i3_news_command="$I3_NEWS_BIN_PATH --plain ${all_args[@]:1}"
    if ! eval $i3_news_command > /dev/null; then
        exit
    fi
    $ZSCROLL_EXE -l $ZSCROLL_WIDTH \
        --delay $ZSCROLL_DELAY \
        --match-command "$i3_news_command" \
        --update-check true \
        --update-interval $ZSCROLL_INTERVAL "$i3_news_command" &
    wait
elif [ "$1" = "bscroll" ]; then
    all_args=("$@")
    params="${all_args[@]:1}"
    BSCROLL_WIDTH=$BSCROLL_WIDTH \
    BSCROLL_INTERVAL=$BSCROLL_INTERVAL \
    BSCROLL_DELAY=$BSCROLL_DELAY \
    I3_NEWS_BIN_PATH=$I3_NEWS_BIN_PATH \
    I3_NEWS_BROWSER_CMD=$I3_NEWS_BROWSER_CMD \
    $BSCROLL_SCRIPT "$params"
# i3 blocks handler
elif [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    url="$($I3_NEWS_BIN_PATH --get-url -c $short_text)"
    if [ -n ${I3_NEWS_BROWSER_CMD+x} ]; then
        $I3_NEWS_BROWSER_CMD $url
    else
        xdg-open $url
    fi
    $I3_NEWS_BIN_PATH -b -c $short_text
elif [ "$1" = "version" ]; then
    cat "$HERE"/VERSION
elif [ "$1" = "--help" ] || [ "$1" = "-h" ]  ; then
    echo "Usage: i3news ?<command> <options>

Commands: open|reload|zscroll|bscroll|version

Options:
  -c, --configs       Snippet configuration or configurations to use
  -s, --i3status      I3status output
  -b, --i3blocks      I3blocks output
  -p, --polybar       Polybar output
  -w, --waybar        Waybar output
  -a, --add-config    Add new i3-news configuration
  -r, --rm-config     Remove existing configuration
  -e, --edit-config   Edit urls for given configuration
      --get-url       Retrieve url for currently displayed headline
      --plain         Plain output
      --debug         Print debug info
  -h, --help          Print help
    "
else
    $I3_NEWS_BIN_PATH $@
fi
