#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"

export PATH="$HERE"/bin:"$HERE"/usr/bin:"$PATH"
export LD_LIBRARY_PATH="$HERE"/usr/lib:"$LD_LIBRARY_PATH"

export I3_NEWS_HOME=$HOME/.config/i3_news
export I3_NEWS_BIN_PATH="$HERE"/usr/local/bin/i3_news
export NEWSBOAT_BIN="$HERE"/usr/local/bin/newsboat
export ZSCROLL_EXE="$HERE"/usr/local/bin/zscroll

if [ -z ${I3_NEWS_BROWSER_CMD+x} ]; then
    export I3_NEWS_BROWSER_CMD=$BROWSER
fi
if [ -z ${ZSCROLL_INTERVAL+x} ]; then
    export ZSCROLL_INTERVAL=10
fi
if [ -z ${ZSCROLL_DELAY+x} ]; then
    export ZSCROLL_DELAY=0.6
fi
if [ -z ${ZSCROLL_WIDTH+x} ]; then
    export ZSCROLL_WIDTH=40
fi

newsboat_reload() {
    if type pgrep > /dev/null; then
        while pgrep newsboat > /dev/null; do sleep 2; done
    fi
    mkdir -p $I3_NEWS_HOME;
    if [ -z "$( ls -A $I3_NEWS_HOME )" ]; then
        echo "No configurations found in " $I3_NEWS_HOME;
        return
    fi
    for dir in $I3_NEWS_HOME/*/
    do
        dir=${dir%*/}
        echo "i3-news: Reloading news for config ${dir##*/}"
        $NEWSBOAT_BIN -x reload -c ${dir}/cache.db -u ${dir}/urls
    done
}

if [ "$1" = "reload" ]; then
    newsboat_reload;
# polybar 
elif [ "$1" = "open" ]; then
    all_args=("$@")
    url="$($I3_NEWS_BIN_PATH --get-url ${all_args[@]:1})"
    if [ -n ${I3_NEWS_BROWSER_CMD+x} ]; then
        $I3_NEWS_BROWSER_CMD $url
    else
        xdg-open $url
    fi
elif [ "$1" = "zscroll" ]; then
    all_args=("$@")
    i3_news_command="$I3_NEWS_BIN_PATH --plain ${all_args[@]:1}"
    $ZSCROLL_EXE -l $ZSCROLL_WIDTH \
        --delay $ZSCROLL_DELAY \
        --match-command "$i3_news_command" \
        --update-check true \
        --update-interval $ZSCROLL_INTERVAL "$i3_news_command" &
    wait
# i3 blocks handler
elif [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    url="$($I3_NEWS_BIN_PATH --get-url -c $short_text)"
    if [ -n ${I3_NEWS_BROWSER_CMD+x} ]; then
        $I3_NEWS_BROWSER_CMD $url
    else
        xdg-open $url
    fi
    $I3_NEWS_BIN_PATH -b -c $short_text
else
    $I3_NEWS_BIN_PATH $@
fi
