#!/bin/bash

if ! type i3_news > /dev/null; then
    echo "i3_news binary not found in the system"
    exit 1
fi


PARAMS="$@"

EMOJI="\U1f300-\U1f5ff\U1f900-\U1f9ff\U1f600-\U1f64f\U1f680-\U1f6ff\U2600-\U26ff\U2700-\U27bf\U1f1e6-\U1f1ff\U1f191-\U1f251\U1f004\U1f0cf\U1f170-\U1f171\U1f17e-\U1f17f\U1f18e\U3030\U2b50\U2b55\U2934-\U2935\U2b05-\U2b07\U2b1b-\U2b1c\U3297\U3299\U303d\U00a9\U00ae\U2122\U23f3\U24c2\U23e9-\U23ef\U25b6\U23f8-\U23fa"

if [ -z ${I3_NEWS_INTERVAL+x} ]; then
    export I3_NEWS_INTERVAL=16
fi
if [ -z ${I3_NEWS_DELAY+x} ]; then
    export I3_NEWS_DELAY=0.5
fi
if [ -z ${I3_NEWS_WIDTH+x} ]; then
    export I3_NEWS_WIDTH=60
fi
if [ -z ${I3_NEWS_CONTINUOUS_SCROLL+x} ]; then
    export I3_NEWS_CONTINUOUS_SCROLL=0
fi
if [ -z ${I3_NEWS_OUTPUT_PANGO+x} ]; then
    export I3_NEWS_OUTPUT_PANGO=0
fi
if [ -z ${I3_NEWS_BIN_PATH+x} ]; then
    export I3_NEWS_BIN_PATH=i3_news
fi


ADD_STR=" | "
ADD_LENGTH=${#ADD_STR}
PROG="$I3_NEWS_BIN_PATH --plain $PARAMS"
SCROLL_POS=0
INS=$(date +%s)
ARTICLES=()

generate_text_line() {
	if [ "$I3_NEWS_CONTINUOUS_SCROLL" -eq 0 ]; then
		article=${ARTICLES[0]}
		out_text="${article}${ADD_STR}${article}${ADD_STR}${article}"
	else
		out_text=""
		for idx in "${!ARTICLES[@]}"
		do
			out_text="$out_text${ARTICLES[$idx]}$ADD_STR"
		done
	fi
	out_text=${out_text:$SCROLL_POS:$I3_NEWS_WIDTH}
	echo "$out_text"

}

get_article() {
	out_text=$(${PROG})
	out_text=$(echo "$out_text" | sed -e "s/&/and/g" -e "s/</lt/g" -e "s/>/gt/g")
	out_text=$(echo "$out_text" | LC_ALL=UTF-8 sed -e "s/[$(printf $EMOJI)]//g")
	out_text=$(echo "$out_text" | sed -e "s/#[a-zA-Z0-9]*//g")
	echo "$out_text"
}

output_text() {
    # echo "<span font_family='monospace'>${TEXT_LINE}</span>"
    if [ "$I3_NEWS_OUTPUT_PANGO" -gt 0 ]; then
        echo "<span font_family='monospace'>$1</span>"
    else
        printf "%s\n" "$1"

    fi

}

if [ "$I3_NEWS_CONTINUOUS_SCROLL" -gt 0 ]; then
	while true; do
        article=$(get_article)
        ARTICLES+=("$article")
		if [ ${#ARTICLES[@]} -eq 5 ]; then
			break
	fi
	done
else
	ARTICLES+=("$(${PROG})")
fi

while true :
do
    NOW=$(date +%s)
	MAX_OFFSET=$((${#ARTICLES[0]} +ADD_LENGTH -1))

	if [ "$I3_NEWS_CONTINUOUS_SCROLL" -gt 0 ]; then 
		if [[ "${SCROLL_POS}" -gt "${MAX_OFFSET}" ]]; then
			SCROLL_POS=0
			unset "${ARTICLES[0]}"
            article=$(get_article)
            ARTICLES+=("$article")
		fi
		TEXT_LINE=$(generate_text_line)

        output_text "$TEXT_LINE"
		SCROLL_POS=$((SCROLL_POS +1))
	else
		if [[ $(("$NOW" - "$INS")) -gt "${I3_NEWS_INTERVAL}" ]]; then
			ARTICLES[0]="$(get_article)"
			INS=$(date +%s)
			SCROLL_POS=0
		fi

		OUT_TEXT=${ARTICLES[0]}
		TEXT_LENGTH=${#OUT_TEXT}

		if [[ "$OUT_TEXT" = "No News" ]]; then
			echo "<span font_family='monospace'>${OUT_TEXT}</span>"
			sleep 1
		fi

		if [[ "$TEXT_LENGTH" -lt "$I3_NEWS_WIDTH" ]]; then
			pad_base=$(("$I3_NEWS_WIDTH" - "$TEXT_LENGTH"))
			pad=$(("$pad_base" / 2))
			rem=$(("$pad" % 2))
			lpad=$(("$pad" + "$rem"))
			TEXT_LINE=$(printf "%0*s%s%0*s" "$lpad" " " "$OUT_TEXT" "$I3_NEWS_WIDTH" " ");
			SCROLL_POS=0
			TEXT_LINE=${TEXT_LINE:$SCROLL_POS:$I3_NEWS_WIDTH}
            output_text "$TEXT_LINE"
		else

			if [[ "${SCROLL_POS}" -gt "${MAX_OFFSET}" ]]; then
				SCROLL_POS=0
			fi

            TEXT_LINE=$(generate_text_line)
            output_text "$TEXT_LINE"
			SCROLL_POS=$((SCROLL_POS +1))
		fi
	fi

    read -t "${I3_NEWS_DELAY}" click
    if [[ $click -eq 1 ]]; then
        cmd="$I3_NEWS_BIN_PATH --get-url $PARAMS"
        url=$($cmd)
        if [ -z ${I3_NEWS_BROWSER_CMD+x} ]; then
            xdg-open "$url" &
        else
            $I3_NEWS_BROWSER_CMD "$url" &
        fi
		ARTICLES[0]="$(get_article)"
        INS=$(date +%s)
        SCROLL_POS=0
        continue
    fi

done
