name: build

on: [push, pull_request]

jobs:
  test:
    name: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Alpine Linux for x86_64 (build arch)
        uses: jirutka/setup-alpine@v1
        with:
          arch: x86_64
          packages: >
            newsboat
          # volumes: ${{ steps.alpine-target.outputs.root-path }}:/mnt/alpine_x64
          shell-name: alpine.sh
      - name: test
        run: ls /home/runner/rootfs/alpine-latest-x86_64/usr/bin
      - name: test
        run: ls /home/runner/rootfs/alpine-latest-x86_64/usr/lib
      - name: test
        run: cd /home/runner/rootfs/alpine-latest-x86_64 && tree
