name: build

on:
  push:
    branches:
      - master
      - develop
    tags:        
      - '*'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - type: normal
            binary_name: i3_news

          - type: self_contained
            binary_name: i3_news_self_contained

    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install desktop-file-utils libfuse2 snapd 

      - name: Install newsboat
        run: sudo snap install newsboat

      - name: Download appimage build tool
        run: |
          wget -nv -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod a+x ./appimagetool-x86_64.AppImage

      - name: Copy required files (self contained)
        run: |
          mkdir -p AppDir/usr/
          cp -Rf /snap/newsboat/current/usr/lib/x86_64-linux-gnu AppDir/usr/lib
          mkdir -p AppDir/usr/local/bin
          cp -Rf /snap/newsboat/current/usr/local/bin/newsboat AppDir/usr/local/bin
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libjson-c.so.4 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libjson-c.so.4.0.0 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libssl.so.1.1 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libsqlite3.so.0 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libdl-2.31.so AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libdl.so.2 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libncursesw.so.6 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libncursesw.so.6.2 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libzstd.so.1 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libzstd.so.1.4.4 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libz.so.1 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libz.so.1.2.11 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libkeyutils.so.1 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libkeyutils.so.1.8 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libhogweed.so.5 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libhogweed.so.5.0 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libnettle.so.7 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libnettle.so.7.0 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libunistring.so.2 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0 AppDir/usr/lib
          cp VERSION AppDir/
          cp scripts/bscroll AppDir/usr/local/bin
        if: contains(matrix.version.type, 'self_contained')

      - name: Copy required files (normal)
        run: |
          mkdir -p AppDir/usr/local/bin
          mkdir -p AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libsqlite3.so.0 AppDir/usr/lib
          cp /snap/core20/current/usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6 AppDir/usr/lib
          cp VERSION AppDir/
          cp scripts/bscroll AppDir/usr/local/bin
        if: contains(matrix.version.type, 'normal')

      - name: Download zscroll
        run: |
          wget -O ./AppDir/usr/local/bin/zscroll https://raw.githubusercontent.com/noctuid/zscroll/master/zscroll
          chmod +x ./AppDir/usr/local/bin/zscroll

      - name: Build i3-news
        run: make build-release

      - name: Copy i3-news binary
        run: cp zig-out/bin/i3_news AppDir/usr/local/bin

      - name: Replace usr references
        run: |
          pushd AppDir
          find usr/ -type f -executable -exec sed -i -e "s|/usr|././|g" {} \;
          popd

      - name: Build appimage
        run: ./appimagetool-x86_64.AppImage AppDir

      - name: Upload AppImage (stable)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: i3-news-x86_64.AppImage
          asset_name: ${{ matrix.version.binary_name }}
          tag: stable
          overwrite: true
        if: github.ref == 'refs/heads/master'

      - name: Upload AppImage (tag)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: i3-news-x86_64.AppImage
          asset_name: ${{ matrix.version.binary_name }}
          tag: ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload AppImage (nightly)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: i3-news-x86_64.AppImage
          asset_name: ${{ matrix.version.binary_name }}
          tag: nightly
          overwrite: true
        if: github.ref == 'refs/heads/develop'
