name: build

on: [push, pull_request]

jobs:
  test:
    name: build
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Alpine Linux for x86_64 (build arch)
        uses: jirutka/setup-alpine@v1
        with:
          arch: x86_64
          packages: >
            build-base
            pkgconf
            lld
            rustup
            newsboat
          volumes: ${{ steps.alpine-target.outputs.root-path }}:/mnt/alpine_x64
          shell-name: alpine.sh
      - name: test
        run: ls /mnt/alpine_x64
