name: build

on: [push, pull_request]

jobs:
  test:
    name: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
          with:
            version: 0.14.1
      - name: Set up Alpine Linux for x86_64 (build arch)
        uses: jirutka/setup-alpine@v1
        with:
          arch: x86_64
          packages: >
            newsboat
          shell-name: alpine.sh
      - name: Copy newsboat files
        run: |
          mkdir -p AppDir/usr/bin
          cp /home/runner/rootfs/alpine-latest-x86_64/usr/bin/newsboat AppDir/usr/bin
          cp -Rf /home/runner/rootfs/alpine-latest-x86_64/usr/lib AppDir
      - name: test
        run: cd AppDir && tree
      - name: test
        run: zig version
    
